[theme]
base = "light"
primaryColor = "#5B2C90"
backgroundColor = "#EDE6F5"
secondaryBackgroundColor = "#F3EDF8"
textColor = "#2B193E"
borderColor = "#DED2EA"
baseRadius = "12px"
buttonRadius = "10px"
headingFontSizes = ["2.5rem", "1.75rem", "1.3rem"]
headingFontWeights = [750, 650, 650]
